name: "Build Test"

on: [ push,pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build_test:
    name: Build Test
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: local

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Format
        run: if [ "$(gofmt -l . | tee >&2 | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Build
        run: make build-all

      - name: Git Diff
        run: if [ "$(git diff | tee >&2 | wc -l)" -gt 0 ]; then exit 1; fi
