name: "Services Test Kodo"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  push:
    paths:
      - 'services/kodo/**'
    tags-ignore:
      - '**'
    branches:
      - '**'
  pull_request:
    paths:
      - 'services/kodo/**'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  services_test_kodo:
    name: "Services Test Kodo"
    runs-on: self-hosted

    strategy:
      matrix:
        go: [ "1.25" ]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Load secret
        uses: 1password/load-secrets-action@v1
        env:
          STORAGE_KODO_CREDENTIAL: op://Engineering/Kodo/testing/credential
          STORAGE_KODO_NAME: op://Engineering/Kodo/testing/name
          STORAGE_KODO_ENDPOINT: op://Engineering/Kodo/testing/endpoint

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test
        env:
          STORAGE_BOS_INTEGRATION_TEST: on
        working-directory: services/kodo
        run: make integration_test
